import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import fetchContentType from "@/lib/strapi/fetchContentType";
import { cn } from "@/lib/utils";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { SessionProvider } from "next-auth/react";
import { AuthProvider } from "@/providers/AuthProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pageData = await fetchContentType('global', { filters: {} }, true);

  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body
        className={cn(
          inter.className,
          "bg-charcoal antialiased h-full w-full"
        )}
      >
        <AuthProvider>
          <Navbar data={pageData.navbar} />
          {children}
          <Footer data={pageData.footer} />
        </AuthProvider>
      </body>
    </html>
  );
}
